name: Flask App Deployment

on:
  push:
    branches:
      - main  # Change this if your branch name is different
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Ensure this file exists

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start Flask App
        run: |
          python 'WEB TO TELE MAIN/Compress.py' &  # Run Flask in the background
          sleep 5  # Wait for the server to start

      - name: Start ngrok and Expose Port
        run: |
          ngrok http 5000 > /dev/null &
          sleep 5  # Give ngrok time to start

      - name: Get ngrok URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep Process Running
        run: tail -f /dev/null  # Prevents GitHub Actions from stopping
