name: Deploy Flask App with Ngrok

on:
  push:
    branches:
      - main  # Change to your branch if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/
        ngrok authtoken "${{ secrets.cr_2tJKtVK9ibLRoAKB0UmcgcIx9TS }}"


    - name: Start Ngrok and Flask App
      run: |
        echo "Starting Ngrok..."
        ngrok http 5000 > /dev/null &
        sleep 5
        curl -s http://localhost:4040/api/tunnels > ngrok_url.json
        export PUBLIC_URL=$(jq -r ".tunnels[0].public_url" ngrok_url.json)
        echo "Ngrok Public URL: $PUBLIC_URL"
        
        echo "Starting Flask App..."
        python "WEB TO TELE MAIN/Compress.py"
